### ISSUE TITLE
web console failing to build on master

### ISSUE THREAD

**Issue by Ben-Owen-3183** [rails/web-console#329]
web console blowing up on master with the following settings.

```
ruby '~> 3.2'
gem 'rails', '~> 7.0.6'
```

Works fine on v4.2.0

Error
```
19:39:07 web.1     | /workspaces/web-console/lib/web_console/railtie.rb:55:in `block in <class:Railtie>': undefined method `deprecators' for #<Review::Application> (NoMethodError)
19:39:07 web.1     | 
19:39:07 web.1     |       app.deprecators[:web_console] = ActiveSupport::Deprecation.new("5.0", "WebConsole")
```

source

```
 initializer "web_console.deprecator" do |app|
     app.deprecators[:web_console] = ActiveSupport::Deprecation.new("5.0", "WebConsole")
 end
```

Not sure what else could be relevent here.
