### PR TITLE
Fix `rake templates:test`

### PR DESCRIPTION
**Pull request by mishina2228**
`rake templates:test` was left to fail for a long time.
This PR will fix it (with a slightly larger number of file changes).
Here are the details:

- Fix for the edge Rails
  - Address the change of ActionView::Base.new in Rails 6 
    - Same change as #304
  - Render templates without `.` in the name 
    - Similar change as #298
    - refs:
      - rails/rails#39164
      - https://stackoverflow.com/questions/68836670/rails-6-1-4-deprecation-warning-rendering-actions-with
  - Check `Rails.logger` is defined 
    - ActionView is in use without Rails at `rake templates:test`
  - `require "action_dispatch"` to use `Mime::Type` 
    - This fixes the following error:
      ```
      ActionView::Template::Error: undefined method `to_sym' for nil:NilClass

                @symbol = symbol.to_sym
                          ^^^^^^^
      ```
- Fix for the edge Rack
  - **Lowercase response headers**
    - The latest rack 3.0 (unreleased) does not accept uppercase headers.
      See rack/rack#1592 for more details.
    - refs:
      - rack/rack#1812
      - rails/sprockets#744
    - It required changes not only to files under `test/`, also to files under `lib/`. 
  - Set content-length header in the `FakeMiddleware`
    - Similar change as #290
- Replace mocha-phantomjs-core with mocha-headless-chrome
  - web-console has ES6 syntax codes introduced in #297 and #308.
  - phantomjs does not support ES6, so it is replaced with [mocha-headless-chrome](https://github.com/direct-adv-interfaces/mocha-headless-chrome).

I ran the test locally and confirmed that it succeeded.
```
$ bundle exec rake templates:test


..............................
30 passing (679ms)
```

### CODE REVIEW

**Comment by gsamokovarov** [comment]
Thanks for all the little details you fixed along the way! 🙇‍♂️
